// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiMotorcycle.Context;

#nullable disable

namespace apiMotorcycle.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20231115170925_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apiMotorcycle.Model.Empresas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("enderecoEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("imagensEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("telefoneEmpresa")
                        .HasColumnType("longtext");

                    b.Property<string>("whatsappEmpresa")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
